name: demo_books
description: Test Flutter project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: 1.15.0
  dio: 4.0.1
  flutter:
    sdk: flutter
  freezed_annotation: 0.15.0
  json_annotation: 4.3.0
  provider: 6.0.1
  shimmer: 2.0.0

dev_dependencies:
  build_runner: 2.1.4
  extra_pedantic: 1.5.0
  flutter_test:
    sdk: flutter
  freezed: 0.15.0+1
  json_serializable: 6.0.1
  mocktail: 0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
